version: '3'

services:
  web:
    build:
      context: ./
      target: web
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - network
    env_file:
      - .env

  api:
    build:
      context: ./
      target: api
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/app
    # depends_on:
    networks:
      - network
    env_file:
      - .env



# volumes:

networks:
  network:
    driver: bridge
